const MILLISECONDS_IN_SECOND = 1000;
const CONFIGS_DIRECTORY = "configs";

const ErrorType = {
    METHOD_NOT_IMPLEMENTED: "Method not implemented!"
};

YOUTUBE_API_VERSION = "v3";
GOOGLE_SHEETS_API_VERSION = "v4";

module.exports = {
    YOUTUBE_API_VERSION,
    GOOGLE_SHEETS_API_VERSION,
    MILLISECONDS_IN_SECOND,
    CONFIGS_DIRECTORY,
    ErrorType
};